### ISSUE TITLE
VWO/VWO.h' file not found

### ISSUE THREAD

**Issue by keshk26** [wingify/vwo-react-native#8]
Hello, 

I am trying to integrate this package for A/B testing. I am getting the following build error in Xcode. I tried using react native link and I also tried manual installation as well. I am using react-native version 0.48.4. Any help would be greatly appreciated!

![screen shot 2018-04-05 at 2 07 27 pm](https://user-images.githubusercontent.com/18268072/38392074-0a65ea66-38db-11e8-9b34-c3559aafa877.png)

**Comment by kaunteya** [comment]
Did you add VWO in podfile?

**Comment by keshk26** [comment]
Yes, added pod 'VWO' to the podfile. Is the cocoapod version and my local cocoapods version not in sync? I am using v1.4.0, if that is any help.

**Comment by kaunteya** [comment]
No. pod version should not be a problem.

If you are integrating VWO in your existing react-native app, can you instead try integrating VWO in a clean new app?

I just tried integrating VWO in a clean new app, and it worked fine.

----
Just to make sure we are on the same page, here is the extract from my command line
```
react-native init t2
cd t2
npm install https://github.com/wingify/vwo-react-native
react-native link vwo-react-native
cd ios
pod init
vim Podfile //Added pod 'VWO'
pod install
open t2.xcworkspace // And run on iPhone
```

**Comment by keshk26** [comment]
After looking at a couple other a/b testing options, I came back to vwo. The above test on a fresh project did build. It must be an issue with being on RN 0.48 but I do not know what it is. I even tried downgrading the cocoapod version to 2.0.0.

**Comment by kaunteya** [comment]
Hey Keshav, after you opened this issue we did some research on what exactly what must be going wrong here.

After digging a lot, we have found out that the reason of this error was `use_frameworks!` which we use in cocoapods to use `Swift` libraries.(If we comment `use_frameworks` everything works fine)

So for now, we have updated the repo and there is slight change in the process of linking of the library.
Instead of using `react-native link vwo-react-native` you have to manually drag the files to your Xcode project. You can find the details [here](http://developers.vwo.com/reference#react-native-guide)
